sudo: false
language: java
addons:
  chrome: stable
before_install:
  # GUI
  # "export DISPLAY=:99.0"
  # "sh -e /etc/init.d/xvfb start"
  # sleep 5
  - bash run.sh &
  - bash waitForServerLoad.sh
  - curl http://localhost:9292
  - res=$?
  - echo $res
  - sleep 3
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  # google chrome standalone driver
  - wget http://chromedriver.storage.googleapis.com/2.36/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
  - sudo chmod a+x /usr/local/bin/chromedriver

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -B -V

jdk:
  - openjdk8
  - oraclejdk8
script:
  - mvn test -Dgpg.skip=true
  - xvfb-run make test
notifications:
  email: false

