sudo: false
language: java
before_install:
  - gem update --system
  - gem install bundler
  - gem install jbundler
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -B -V
jdk:
  - openjdk7
  - oraclejdk8
script:
  - bundle exec jbundle install && bundle exec rake war && bundle exec rake jardist
  - mvn test -Dgpg.skip=true
notifications:
  email: false

