sudo: false
language: java
addons:
  chrome: stable
before_install:
  - gem update --system
  - gem install bundler
  - gem install jbundler
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9292 http://localhost &
  # google chrome standalone driver
  - wget http://chromedriver.storage.googleapis.com/2.37/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
  - sudo chmod a+x /usr/local/bin/chromedriver
  # start the server

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -B -V
jdk:
  - oraclejdk8
  - openjdk7
script:
  - mvn test -Dgpg.skip=true
notifications:
  email: false

