sudo: false
language: java
addons:
  chrome: stable
before_install:
  - gem update --system
  - gem install bundler
  - gem install jbundler
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9292 http://localhost &
  # google chrome standalone driver
  - wget http://chromedriver.storage.googleapis.com/2.37/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
  - sudo chmod a+x /usr/local/bin/chromedriver

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -B -V
  # download and use jruby
  - wget https://repo1.maven.org/maven2/org/jruby/jruby-dist/9.1.16.0/jruby-dist-9.1.16.0-bin.zip
  - unzip jruby-dist-9.1.16.0-bin.zip
  - mv jruby-dist-9.1.16.0-bin.zip ~/
  # start the server
  - git clone https://github.com/redmyers/484_P7_1-GUI.git
  - git checkout origin/Header_Addition
  - export PATH=~/jruby/bin:$PATH
  - gem install bundler
  - bundle install
  - jruby -S jbundle install
  - jruby -G -r jbundler -S rackup
jdk:
  - oraclejdk8
  - openjdk7
script:
  - mvn test -Dgpg.skip=true
notifications:
  email: false

