sudo: false
language: java
before_install:
  - gem update --system
  - gem install bundler
  - gem install jbundler
jdk:
  - oraclejdk8
  - openjdk7
script: bundle exec jbundle install && bundle exec rake war && bundle exec rake jardist
notifications:
  email: false
